spring.application.name=receipt-deliveries-frontend

server.port=3200

receipt-deliveries.api.base-url=${BACKEND_URL:http://localhost:3100}

vaadin.launch-browser=true
vaadin.launch-browser-delay=0